name: 'mirror'
on:
  push:
    branches:
        - __mirror
  schedule:
    # Run everyday at 4 AM UTC
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror
        id: mirror
        uses: bridgelightcloud/github-mirror-action@e5620f9dfa4217be90d7a2bfc4c5b4256df8334f
        with:
          origin: 'https://codeberg.org/TemariVirus/zxc'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
